name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: tests-go-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            tests-go-${{ runner.os }}-
      - name: Run tests
        if: matrix.run_on_pull_requests || github.event_name != 'pull_request'
        shell: bash
        run: |
          make test
